#!/usr/bin/env python3
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ft_otp                                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yitani <yitani@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/05 09:41:01 by yitani            #+#    #+#              #
#    Updated: 2025/11/06 09:20:37 by yitani           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

import time
import hmac
import hashlib
import getpass
import argparse
from cryptography.fernet import Fernet
from sys import argv
from os import urandom
import base64
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

def	validateFile(pathToFile):
	try:
		f = open(pathToFile)
		content = f.read()
		f.close()
		content = content.strip()
	except Exception:
		print("Error was encountered opening file")
		exit(1)
	if len(content) < 64:
		print("Less than 64 values found")
		exit(1)
	for c in content:
		if not c in ("0123456789aAbBcCdDeEfF"):
			print("Error non Hexa value found:", c)
			exit(1)
	return content

def	deriveKey(password, salt):
	pbkd = PBKDF2HMAC(algorithm=hashes.SHA256(), salt=salt, backend=default_backend(), iterations=10000, length=32)
	return base64.urlsafe_b64encode(pbkd.derive(password.encode()))

def	generateOtp(decryptedData):
	timeCounter = time.time() // 30
	newKey = bytes.fromhex(decryptedData)
	counterBytes = int(timeCounter).to_bytes(8, byteorder="big")
	hmacResult = hmac.new(newKey, counterBytes, hashlib.sha1).digest()
	offSet = hmacResult[-1] & 0x0f
	truncated = hmacResult[offSet:offSet+4]
	code = int.from_bytes(truncated, byteorder='big')
	code = code & 0x7fffffff
	otp = code % 1000000
	return str(otp).zfill(6)

parser = argparse.ArgumentParser()
parser.add_argument('-k', '--key', type=str)
parser.add_argument('-g', '--file', type=str)
args = parser.parse_args()

if '-g' in argv and '-k' in argv:
	exit(1)

if '-g' in argv:
	content = validateFile(args.file)
	password = getpass.getpass("Password: ")
	salt = urandom(16)
	keyGen = deriveKey(password, salt)
	fernetObj = Fernet(keyGen)
	encryptedData = fernetObj.encrypt(content.encode())
	try:
		file = open("ft_otp.key", "wb")
		file.write(salt)
		file.write(encryptedData)
		file.close()
	except Exception:
		print("Error creating encrypted file")
		exit(1)
	print("Key was successfully saved in ft_otp.key.")
	exit(0)
else:
	try:
		file = open(args.key, "rb")
		salt = file.read(16)
		encryptedData = file.read()
		file.close()
	except Exception:
		print("Error opening or reading file")
		exit(1)
	password = getpass.getpass("Password: ")
	key = deriveKey(password, salt)
	fernetObj = Fernet(key)
	try:
		decryptedData = fernetObj.decrypt(encryptedData).decode()
	except Exception:
		print("Error wrong password")
		exit(1)
	otp = generateOtp(decryptedData)
	print(otp)